### ISSUE TITLE
 global is not defined

### ISSUE THREAD

**Issue by almaz1213** [zxpsuper/qrcode-with-logos#10]
the line
```
var QRCode = require("qrcode");
```
in your module causes "global is not defined".

package.json in my case:
```
...
"dependencies": {
    "@angular/common": "~9.0.4",
    "@angular/core": "~9.0.4",
...
```

```
declare var global: any;
```
in my component doesn't help

**Comment by zxpsuper** [comment]
> the line
> 
> ```
> var QRCode = require("qrcode");
> ```
> 
> in your module causes "global is not defined".
> 
> package.json in my case:
> 
> ```
> ...
> "dependencies": {
>     "@angular/common": "~9.0.4",
>     "@angular/core": "~9.0.4",
> ...
> ```
> 
> ```
> declare var global: any;
> ```
> 
> in my component doesn't help

There are something wrong in "qrcode" dependencies. I will delete it  in the future. You can try to use esm format. For example
```js
import QrCodeWithLogo from 'qrcode-with-logos'
```

**Comment by diamo1213** [comment]
```
var QRCode = require("qrcode");
```
inside yor module not in my code. so you should use esm format. but i use other other module now
