### ISSUE TITLE
能否支持一下vite2+vue3 构建的项目

### ISSUE THREAD

**Issue by naimao001** [zxpsuper/qrcode-with-logos#11]

**Comment by Haok9800** [comment]
请问你怎么解决的？还是用的其他插件。谢谢

**Comment by Haok9800** [comment]
> _No description provided._

请问你怎么解决的？还是用的其他插件。谢谢

**Comment by Haok9800** [comment]
请问你是怎么解决的，还是用的其他插件？谢谢

**Comment by zxpsuper** [comment]
> _No description provided._

我试了一下是可以使用的呀？请问是遇到什么问题吗？
