### ISSUE TITLE
wide logo

### ISSUE THREAD

**Issue by AliKholmatov** [zxpsuper/qrcode-with-logos#13]
Hi! Could you help with logo size ?,becouse 
![image](https://user-images.githubusercontent.com/87648847/151191465-b028e5e8-9516-4a8f-96c9-bebf087c5c6d.png)
but in this library (https://github.com/kozakdenys/qr-code-styling) the same image looks 
![image](https://user-images.githubusercontent.com/87648847/151191631-5acb398c-b987-45da-9480-b79cca5abdb3.png)
We prefer use your library

**Comment by AliKholmatov** [comment]
@zxpsuper @jinyang1994

**Comment by zxpsuper** [comment]
> Hi! Could you help with logo size ?,becouse ![image](https://user-images.githubusercontent.com/87648847/151191465-b028e5e8-9516-4a8f-96c9-bebf087c5c6d.png) but in this library (https://github.com/kozakdenys/qr-code-styling) the same image looks ![image](https://user-images.githubusercontent.com/87648847/151191631-5acb398c-b987-45da-9480-b79cca5abdb3.png) We prefer use your library

I think you can copy the source code，and change the file(draw-logo.ts) to customize your requirements.

![image](https://user-images.githubusercontent.com/28730619/154183162-a1f33ca1-5555-43a5-88c1-a3b34d99351d.png)

You can change the width and height of logo

**Comment by AliKholmatov** [comment]
your suggestion it's about using your lib according to our requirements with adding changes. I think it's not good way.  So your lib doesn't support this customization? @zxpsuper

**Comment by zxpsuper** [comment]
> your suggestion it's about using your lib according to our requirements with adding changes. I think it's not good way. So your lib doesn't support this customization? @zxpsuper

Yes. At present, the length width ratio of logo is 1:1. I will consider adding this customization function in the future
