### ISSUE TITLE
Promise never throw reject when generate image failed

### ISSUE THREAD

**Issue by JenovaSolier** [zxpsuper/qrcode-with-logos#17]
```
`let qrLogo = new IQrCodeWithLogo({
                content: contact.linkURL,
                width: 380,
                image: image,
                logo: {
                    src: this.remoteUrl+ imageName + '.png'
                }
            });`
```
when I can't download the logo, I don't know if the QR is generated or not.

**Comment by zxpsuper** [comment]
> download

it has generated when logo cannot be download. and it will loss logo, such as: 
![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/3f1eb22a-fd51-4e1f-ba9c-e504a408698a)
