### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by despin** [zxpsuper/qrcode-with-logos#25]
Sorry, can you release a new version of the NPM package? The last version is from 2020, and since then there was various fixes that where added

**Comment by zxpsuper** [comment]
> Sorry, can you release a new version of the NPM package? The last version is from 2020, and since then there was various fixes that where added

new version 0.0.5 has been published!

**Comment by zxpsuper** [comment]
> Sorry, can you release a new version of the NPM package? The last version is from 2020, and since then there was various fixes that where added

new version 1.0.5 has been published!
