### ISSUE TITLE
`getImage()` promise never gets resolved

### ISSUE THREAD

**Issue by kevinkosterr** [zxpsuper/qrcode-with-logos#37]
So I've just found out `toImage()` is deprecated, however when trying to switch to `getImage()` the code never reaches the `.then()` block. Thus, the promise never gets resolved. 

So given the example in the docs:
```javascript
let qrcode = new QrCodeWithLogo({
  canvas: document.getElementById("canvas"),
  content: "https://github.com/zxpsuper",
  width: 380,
  image: document.getElementById("image"),
  logo: {
    src: "https://avatars1.githubusercontent.com/u/28730619?s=460&v=4"
  }
});

qrcode.getImage().then(image => {
  // code execution never gets here
});
```

**Comment by zxpsuper** [comment]
Is your version v1.1.0? 
I can't reproduce this problem on my device. I can log it as shown in the picture.

![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/ad84b12d-7674-4ebc-82b5-21aa1e9e06b5)

Maybe something wrong inside and you can use "onError" to catch the error and fix it.

**Comment by zxpsuper** [comment]
I find it.
Add the default options and it will be normal to use.
![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/20c93ae4-0079-4c2b-b4bf-a8d4c2601bd1)
I will fix it in next version! Thank you !

**Comment by kevinkosterr** [comment]
@zxpsuper awesome. Perhaps it would be a good idea to reject the Promise for `getImage()` whenever an issue occurs?

**Comment by caprica** [comment]
Same for getCanvas() in fact.

**Comment by zxpsuper** [comment]
> @zxpsuper awesome. Perhaps it would be a good idea to reject the Promise for `getImage()` whenever an issue occurs?

There is global error catching that you can use `onError` to deal with it.
