### ISSUE TITLE
Feature: Setting background and foreground colours

### ISSUE THREAD

**Issue by AmoabaKelvin** [zxpsuper/qrcode-with-logos#38]

**Comment by zxpsuper** [comment]
It has been implemented! You can set `nodeQrCodeOptions.color` to change background and foreground colours.
For example:
```js
new QrCodeWithLogo({
  canvas: document.getElementById("canvas"),
  content: "https://github.com/zxpsuper",
  width: 380,
  logo: {
    src: "https://avatars1.githubusercontent.com/u/28730619?s=460&v=4"
  },
  nodeQrCodeOptions: {
    color: {
        light: "#eee",
        dark: "#f00"
      }
  },
  cornersOptions: {},
  dotsOptions: {}
})
```
The result is that:
![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/390ba874-8348-45ac-b5f9-86d3a53cf038)

**Comment by zxpsuper** [comment]
> _No description provided._
It has been implemented!😄

**Comment by zxpsuper** [comment]
@AmoabaKelvin It has been implemented! 😄

**Comment by AmoabaKelvin** [comment]
Super, thanks mate!

**Comment by AmoabaKelvin** [comment]
![CleanShot 2024-07-10 at 09 19 18@2x](https://github.com/zxpsuper/qrcode-with-logos/assets/97001695/d769fec5-765e-42e2-85ff-6f9fb2f84537)
Also it looks kinda blurry and not soo sharp, is there any reason for that @zxpsuper
