### ISSUE TITLE
Loaded QRCode not sharp enough

### ISSUE THREAD

**Issue by AmoabaKelvin** [zxpsuper/qrcode-with-logos#39]
Creating a qrcode and rendering on a page makes it look kinda blurred. It does not look soo sharp

![image](https://github.com/zxpsuper/qrcode-with-logos/assets/97001695/66927a8c-67fe-48f8-8483-b5c27a79b8aa)

**Comment by zxpsuper** [comment]
@AmoabaKelvin I think that maybe width 380 is too small so that qrcode is not sharp enough.

I set the width to 100 and it looks better.

```js
let qrcode = new QrCodeWithLogo({
    content: "https://github.com/zxpsuper",
    width: 1000,
    image: document.getElementById("image"),
    logo: {
      src: 'https://avatars.githubusercontent.com/u/28730619?v=4'
    },
    dotsOptions: {
      type: 'dot'
    },
    cornersOptions: {
      type: 'circle-diamond'
    },
    nodeQrCodeOptions: {
      margin: 20
    }
  });
```
![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/03c0f6a3-a7dd-487f-af2d-b36f7283bb9b)
