### ISSUE TITLE
logo just cover qrcode's center section

### ISSUE THREAD

**Issue by cnzyan** [zxpsuper/qrcode-with-logos#41]
when add a logo,logo just cover qrcode's center section,cause qrcode cannot be scanned properly.why nobody find out this situation?

**Comment by zxpsuper** [comment]
@cnzyan Is your version `v1.1.0` ?

At version `v1.1.0`, this situation is relatively rare.

**Comment by cnzyan** [comment]
thank you，i will download new version and try



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 17, 2024 09:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zxpsuper/qrcode-with-logos] logo just cover qrcode's centersection (Issue #41)




 
@cnzyan Is your version v1.1.0 ?
 
At version v1.1.0, this situation is relatively rare.
