### ISSUE TITLE
Option to change background color

### ISSUE THREAD

**Issue by jayademola** [zxpsuper/qrcode-with-logos#42]
This issue proposes adding a setting to allow users to change the background color and/or image to their preference.

**Comment by zxpsuper** [comment]
> This issue proposes adding a setting to allow users to change the background color and/or image to their preference.

It has been implemented! You can set `nodeQrCodeOptions.color` to change background and foreground colours.
For example:
```js
new QrCodeWithLogo({
  canvas: document.getElementById("canvas"),
  content: "https://github.com/zxpsuper",
  width: 380,
  logo: {
    src: "https://avatars1.githubusercontent.com/u/28730619?s=460&v=4"
  },
  nodeQrCodeOptions: {
    color: {
        light: "#eee",
        dark: "#f00"
      }
  },
  cornersOptions: {},
  dotsOptions: {}
})
```
The result is that:
![image](https://github.com/zxpsuper/qrcode-with-logos/assets/28730619/390ba874-8348-45ac-b5f9-86d3a53cf038)

**Comment by zxpsuper** [comment]
Background image is not support now!
