### ISSUE TITLE
Src logo with local image doesnt work

### ISSUE THREAD

**Issue by josuasimatupang** [zxpsuper/qrcode-with-logos#45]
Local image doesnt work, implement with Next js

![image](https://github.com/user-attachments/assets/58266ec4-2b8c-46e3-bb01-395e29e6cfea)

**Comment by zxpsuper** [comment]
> Local image doesnt work, implement with Next js
> 
> ![image](https://private-user-images.githubusercontent.com/143980457/354540648-58266ec4-2b8c-46e3-bb01-395e29e6cfea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDgxMzksIm5iZiI6MTcyMjkwNzgzOSwicGF0aCI6Ii8xNDM5ODA0NTcvMzU0NTQwNjQ4LTU4MjY2ZWM0LTJiOGMtNDZlMy1iYjAxLTM5NWUyOWU2Y2ZlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwMTMwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGVmODJkYmVkMjAyMzE1OWMwOTBjOTdiY2E5N2ZiMjEwZGM3NzM3MzU2Mjc0NDhkMTI3ZGE3ZDFkY2VkOGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CDH_QfS3QqRx9QGHCg3DiDC3xq3ePYo-QFEWG3T8uF4)

I think may be you input `'require('../assets/image.png')'` as a string so that it cann't be loaded.

try this:
```js
logo: {
  src: require('../../../assets/images/paynow-logo.png')
}
```
instead of:
```js
logo: {
  src: 'require('../../../assets/images/paynow-logo.png')'
}
```
😄😄😄
