### ISSUE TITLE
Request: Resize Logo

### ISSUE THREAD

**Issue by honkeatbb** [zxpsuper/qrcode-with-logos#46]
I have integrated the library but the logo seems to be small. Would be nice if there is option to adjust the logo size.

![image](https://github.com/user-attachments/assets/423b107d-0995-4ded-b9de-f729f0fa7c49)

**Comment by zxpsuper** [comment]
It autojust the logo size.
You can set `nodeQrCodeOptions.errorCorrectionLevel = “H”`, the logo will be larger than before.
@honkeatbb

**Comment by honkeatbb** [comment]
Noted, thanks!
