### ISSUE TITLE
Logo 'src' property is required

### ISSUE THREAD

**Issue by iPavlikov** [zxpsuper/qrcode-with-logos#47]
Is it possible to make logo 'src' property optional? If it is not provided, then draw regular QR code.

**Comment by zxpsuper** [comment]
Yes, it is. Now you not provide the `logo` option, it will draw regular QR code in latest version.

```js
new QrCodeWithLogo({
  content: "https://github.com/zxpsuper",
  width: 1024,
  image: document.getElementById("image"),
  // logo: {
  //     src: this.logo
  //},
});
```
![image](https://github.com/user-attachments/assets/2a2247a0-da1a-47d5-85a6-6894b13494c4)

@iPavlikov
