### ISSUE TITLE
可以实现黑色主题吗

### ISSUE THREAD

**Issue by anthhub** [zxpsuper/qrcode-with-logos#48]
可以实现黑色主题吗，就是点的颜色和现在正好相反

**Comment by zxpsuper** [comment]
> 可以实现黑色主题吗，就是点的颜色和现在正好相反

@anthhub 支持的，通过配置实现 nodeQrCodeOptions.color.dark 和 nodeQrCodeOptions.color.light。
详情可以查看文档：https://zxpsuper.github.io/qrcode-with-logos/guide/options.html#nodeqrcodeoptions-color-dark
