### ISSUE TITLE
dotsOptions

### ISSUE THREAD

**Issue by subarashii-huch09** [zxpsuper/qrcode-with-logos#58]
Hi @zxpsuper ,

Thanks for this great library!  ⭐️
Is there any way to adjust the dots size/radius, making them bigger ?

**Comment by zxpsuper** [comment]
> Hi @zxpsuper ,
> 
> Thanks for this great library! ⭐️ Is there any way to adjust the dots size/radius, making them bigger ?

@subarashii-huch09 
You mean corner?🤔 You can change cornersOption to do that.
![image](https://github.com/user-attachments/assets/0eed0d4c-2b95-4111-b09c-8989bf9d47e1)

**Comment by subarashii-huch09** [comment]
@zxpsuper  dots - can their size be adjusted ?

**Comment by subarashii-huch09** [comment]
> > Hi @zxpsuper ,
> > Thanks for this great library! ⭐️ Is there any way to adjust the dots size/radius, making them bigger ?
> 
> @subarashii-huch09 You mean corner?🤔 You can change cornersOption to do that. ![image](https://private-user-images.githubusercontent.com/28730619/393197834-0eed0d4c-2b95-4111-b09c-8989bf9d47e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MTkwNzAsIm5iZiI6MTczMzYxODc3MCwicGF0aCI6Ii8yODczMDYxOS8zOTMxOTc4MzQtMGVlZDBkNGMtMmI5NS00MTExLWIwOWMtODk4OWJmOWQ0N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAwNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzY2NiM2M2NGE2MmNlODQyODcyNjBjMGMwZGJhY2E0MzYzZTRmNzM1YjZmNzBlMDc2MTdmNDg2NGQ0NmNkNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MTQsLO24KiQO7vOdL8_TMGN64yxyY1CG_UMtPIKDYzA)

@zxpsuper dots - can their size be adjusted ?

**Comment by zxpsuper** [comment]
> > > Hi @zxpsuper ,
> > > Thanks for this great library! ⭐️ Is there any way to adjust the dots size/radius, making them bigger ?
> > 
> > 
> > @subarashii-huch09 You mean corner?🤔 You can change cornersOption to do that. ![image](https://private-user-images.githubusercontent.com/28730619/393197834-0eed0d4c-2b95-4111-b09c-8989bf9d47e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MTkwNzAsIm5iZiI6MTczMzYxODc3MCwicGF0aCI6Ii8yODczMDYxOS8zOTMxOTc4MzQtMGVlZDBkNGMtMmI5NS00MTExLWIwOWMtODk4OWJmOWQ0N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAwNDYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzY2NiM2M2NGE2MmNlODQyODcyNjBjMGMwZGJhY2E0MzYzZTRmNzM1YjZmNzBlMDc2MTdmNDg2NGQ0NmNkNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MTQsLO24KiQO7vOdL8_TMGN64yxyY1CG_UMtPIKDYzA)
> 
> @zxpsuper dots - can their size be adjusted ?

I'm sorry it doesn't support.😥
