### ISSUE TITLE
different qr code style

### ISSUE THREAD

**Issue by arpu** [zxpsuper/qrcode-with-logos#8]
Hey,

would it be possible to use differnt style qr codes like the google chrome dev inbuild
![Bildschirmfoto von 2020-10-09 16-28-26](https://user-images.githubusercontent.com/14173/95634394-1a6c4580-0a8a-11eb-83bf-e54e5d4374a9.png)

**Comment by zxpsuper** [comment]
> Hey,
> 
> would it be possible to use differnt style qr codes like the google chrome dev inbuild ![Bildschirmfoto von 2020-10-09 16-28-26](https://user-images.githubusercontent.com/14173/95634394-1a6c4580-0a8a-11eb-83bf-e54e5d4374a9.png)

I am sorry. There are no plans to achieve it at present.

**Comment by zxpsuper** [comment]
> Hey,
> 
> would it be possible to use differnt style qr codes like the google chrome dev inbuild ![Bildschirmfoto von 2020-10-09 16-28-26](https://user-images.githubusercontent.com/14173/95634394-1a6c4580-0a8a-11eb-83bf-e54e5d4374a9.png)

I am pleased to tell you that it now supports custom styles and colors. Please upgrade version 1.1.0.
